import { render } from '@testing-library/react'
import HeadMeta from './HeadMeta';

jest.mock('next/head', () => ({
  __esModule: true,
  default: ({ children }: { children: Array<React.ReactElement> }) => {
    return <>{children}</>;
  },
}));

describe('Components: HeadMeta', () => {
  it('renders a meta head correctly without props', () => {
    const { container } = render(<HeadMeta />);
    const title = container.querySelector('title');
    const meta = container.querySelector('meta');
    expect(title?.textContent).toBe('My Favorites Cities');
    expect(meta?.getAttribute('content')).toBe('Generated by create next app');
  })

  it('renders a meta head correctly with props', () => {
    const { container } = render(<HeadMeta title='New meta title' />);
    const title = container.querySelector('title');
    const meta = container.querySelector('meta');
    expect(title?.textContent).toBe('New meta title');
    expect(meta?.getAttribute('content')).toBe('Generated by create next app');
  })
});
